version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "dependabot"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
