apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-gs-ping
  namespace: docker-gs-ping
spec:
  chart:
    spec:
      version: "1.4.*"
  test:
    enable: false
  values:
    autoscaling:
      enabled: true
      minReplicas: 4
      maxReplicas: 6
    ingress:
      annotations:
        ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - host: docker-gs-ping.production
          paths:
            - path: /
              pathType: ImplementationSpecific
