apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-gs-ping
  namespace: docker-gs-ping
spec:
  releaseName: docker-gs-ping
  chart:
    spec:
      chart: docker-gs-ping
      sourceRef:
        kind: HelmRepository
        name: docker-gs-ping
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default values
  # https://github.com/unleftie/docker-gs-ping/blob/main/charts/docker-gs-ping/values.yaml
  values:
    podLabels:
      cicd: flux
    ingress:
      enabled: true
