apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-gs-ping
  namespace: docker-gs-ping
spec:
  chart:
    spec:
      chart: docker-gs-ping
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: docker-gs-ping
      version: 1.4.1
  interval: 1m0s # FIXME: revert to 50m
  install:
    remediation:
      retries: 3
  # upgrade:
  #   remediation:
  #     retries: 3
  # Default values
  # https://github.com/unleftie/docker-gs-ping/blob/main/charts/docker-gs-ping/values.yaml
  values:
    podLabels:
      cicd: flux
    ingress:
      enabled: true
      className: nginx
