apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: docker-gs-ping
  namespace: docker-gs-ping
spec:
  interval: 1m # FIXME: revert to 50m
  url: https://unleftie.github.io/docker-gs-ping
