apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-gs-ping
  namespace: docker-gs-ping
spec:
  chart:
    spec:
      version: ">=1.0.0"
  test:
    enable: false
  values:
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
    ingress:
      annotations:
        ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - host: docker-gs-ping.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
